//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int ano { get; set; }
        public int per { get; set; }
        public string codramo { get; set; }
        public string codsecc { get; set; }
        public string codalu { get; set; }
        public Nullable<decimal> nf { get; set; }
        public string estado { get; set; }
    
        public virtual ramo ramo { get; set; }
    }
}
