//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dalc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_vcentralEntities : DbContext
    {
        public db_vcentralEntities()
            : base("name=db_vcentralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<malla> malla { get; set; }
        public virtual DbSet<nota> nota { get; set; }
        public virtual DbSet<ramo> ramo { get; set; }
    
        public virtual ObjectResult<sp_carreras_Result> sp_carreras()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_carreras_Result>("sp_carreras");
        }
    
        public virtual ObjectResult<sp_mallacarrera_Result> sp_mallacarrera(string codcarr)
        {
            var codcarrParameter = codcarr != null ?
                new ObjectParameter("codcarr", codcarr) :
                new ObjectParameter("codcarr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mallacarrera_Result>("sp_mallacarrera", codcarrParameter);
        }
    
        public virtual ObjectResult<sp_ramos_Result> sp_ramos(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ramos_Result>("sp_ramos", idParameter);
        }
    
        public virtual ObjectResult<sp_rut_Result> sp_rut(string rut)
        {
            var rutParameter = rut != null ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rut_Result>("sp_rut", rutParameter);
        }
    }
}
