//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umas.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class malla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public malla()
        {
            this.alumno = new HashSet<alumno>();
        }
    
        public long id_malla { get; set; }
        public string codcarr { get; set; }
        public string codramo { get; set; }
        public Nullable<int> codsecc { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual carrera carrera { get; set; }
        public virtual ramo ramo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno> alumno { get; set; }
    }
}
