//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umas.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion_ramos
    {
        public int id_asignacion { get; set; }
        public int id_curso_moodle { get; set; }
        public int id_carrera { get; set; }
        public int id_malla { get; set; }
    }
}
