//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nota3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CarrerasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Carreras", ReplyAction="*")]
        nota3.ServiceReference1.CarrerasResponse Carreras(nota3.ServiceReference1.CarrerasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Carreras", ReplyAction="*")]
        System.Threading.Tasks.Task<nota3.ServiceReference1.CarrerasResponse> CarrerasAsync(nota3.ServiceReference1.CarrerasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codcarr del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MallaCarrera", ReplyAction="*")]
        nota3.ServiceReference1.MallaCarreraResponse MallaCarrera(nota3.ServiceReference1.MallaCarreraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MallaCarrera", ReplyAction="*")]
        System.Threading.Tasks.Task<nota3.ServiceReference1.MallaCarreraResponse> MallaCarreraAsync(nota3.ServiceReference1.MallaCarreraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarrerasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Carreras", Namespace="http://tempuri.org/", Order=0)]
        public nota3.ServiceReference1.CarrerasRequestBody Body;
        
        public CarrerasRequest() {
        }
        
        public CarrerasRequest(nota3.ServiceReference1.CarrerasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CarrerasRequestBody {
        
        public CarrerasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarrerasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarrerasResponse", Namespace="http://tempuri.org/", Order=0)]
        public nota3.ServiceReference1.CarrerasResponseBody Body;
        
        public CarrerasResponse() {
        }
        
        public CarrerasResponse(nota3.ServiceReference1.CarrerasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CarrerasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CarrerasResult;
        
        public CarrerasResponseBody() {
        }
        
        public CarrerasResponseBody(System.Xml.Linq.XElement CarrerasResult) {
            this.CarrerasResult = CarrerasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MallaCarreraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MallaCarrera", Namespace="http://tempuri.org/", Order=0)]
        public nota3.ServiceReference1.MallaCarreraRequestBody Body;
        
        public MallaCarreraRequest() {
        }
        
        public MallaCarreraRequest(nota3.ServiceReference1.MallaCarreraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MallaCarreraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codcarr;
        
        public MallaCarreraRequestBody() {
        }
        
        public MallaCarreraRequestBody(string codcarr) {
            this.codcarr = codcarr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MallaCarreraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MallaCarreraResponse", Namespace="http://tempuri.org/", Order=0)]
        public nota3.ServiceReference1.MallaCarreraResponseBody Body;
        
        public MallaCarreraResponse() {
        }
        
        public MallaCarreraResponse(nota3.ServiceReference1.MallaCarreraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MallaCarreraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement MallaCarreraResult;
        
        public MallaCarreraResponseBody() {
        }
        
        public MallaCarreraResponseBody(System.Xml.Linq.XElement MallaCarreraResult) {
            this.MallaCarreraResult = MallaCarreraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : nota3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<nota3.ServiceReference1.WebService1Soap>, nota3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nota3.ServiceReference1.CarrerasResponse nota3.ServiceReference1.WebService1Soap.Carreras(nota3.ServiceReference1.CarrerasRequest request) {
            return base.Channel.Carreras(request);
        }
        
        public System.Xml.Linq.XElement Carreras() {
            nota3.ServiceReference1.CarrerasRequest inValue = new nota3.ServiceReference1.CarrerasRequest();
            inValue.Body = new nota3.ServiceReference1.CarrerasRequestBody();
            nota3.ServiceReference1.CarrerasResponse retVal = ((nota3.ServiceReference1.WebService1Soap)(this)).Carreras(inValue);
            return retVal.Body.CarrerasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nota3.ServiceReference1.CarrerasResponse> nota3.ServiceReference1.WebService1Soap.CarrerasAsync(nota3.ServiceReference1.CarrerasRequest request) {
            return base.Channel.CarrerasAsync(request);
        }
        
        public System.Threading.Tasks.Task<nota3.ServiceReference1.CarrerasResponse> CarrerasAsync() {
            nota3.ServiceReference1.CarrerasRequest inValue = new nota3.ServiceReference1.CarrerasRequest();
            inValue.Body = new nota3.ServiceReference1.CarrerasRequestBody();
            return ((nota3.ServiceReference1.WebService1Soap)(this)).CarrerasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nota3.ServiceReference1.MallaCarreraResponse nota3.ServiceReference1.WebService1Soap.MallaCarrera(nota3.ServiceReference1.MallaCarreraRequest request) {
            return base.Channel.MallaCarrera(request);
        }
        
        public System.Xml.Linq.XElement MallaCarrera(string codcarr) {
            nota3.ServiceReference1.MallaCarreraRequest inValue = new nota3.ServiceReference1.MallaCarreraRequest();
            inValue.Body = new nota3.ServiceReference1.MallaCarreraRequestBody();
            inValue.Body.codcarr = codcarr;
            nota3.ServiceReference1.MallaCarreraResponse retVal = ((nota3.ServiceReference1.WebService1Soap)(this)).MallaCarrera(inValue);
            return retVal.Body.MallaCarreraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nota3.ServiceReference1.MallaCarreraResponse> nota3.ServiceReference1.WebService1Soap.MallaCarreraAsync(nota3.ServiceReference1.MallaCarreraRequest request) {
            return base.Channel.MallaCarreraAsync(request);
        }
        
        public System.Threading.Tasks.Task<nota3.ServiceReference1.MallaCarreraResponse> MallaCarreraAsync(string codcarr) {
            nota3.ServiceReference1.MallaCarreraRequest inValue = new nota3.ServiceReference1.MallaCarreraRequest();
            inValue.Body = new nota3.ServiceReference1.MallaCarreraRequestBody();
            inValue.Body.codcarr = codcarr;
            return ((nota3.ServiceReference1.WebService1Soap)(this)).MallaCarreraAsync(inValue);
        }
    }
}
